"""Build-time Readex Pro glyph masks; runtime needs no font service or canvas.

Requires Pillow with RAQM, fonttools and brotli. Uses the bundled OFL fonts.
"""
import base64
import io
import json
import zlib
from pathlib import Path

from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]


def font(script, size, weight):
    ft = TTFont(ROOT / f"public/fonts/readex-pro-{script}-wght-normal.woff2")
    ft = instantiateVariableFont(ft, {"wght": weight}, inplace=True)
    ft.flavor = None
    buf = io.BytesIO()
    ft.save(buf)
    buf.seek(0)
    return ImageFont.truetype(buf, size)


def glyph(text, face, rtl=False):
    options = {"direction": "rtl", "language": "ar"} if rtl else {}
    box = face.getbbox(text, **options)
    im = Image.new("L", (box[2] - box[0] + 4, box[3] - box[1] + 4))
    ImageDraw.Draw(im).text((2 - box[0], 2 - box[1]), text, font=face, fill=255, **options)
    return {"w": im.width, "h": im.height,
            "data": base64.b64encode(zlib.compress(im.tobytes(), 9)).decode()}


masks = {}
for height in (144, 112):
    digits = font("latin", round(height * 1.65), 650)
    percent = font("latin", round(height * .82), 500)
    arabic = font("arabic", round(height * .285), 500)
    for n in range(10):
        masks[f"{height}:{n}"] = glyph(str(n), digits)
    masks[f"{height}:%"] = glyph("%", percent)
    masks[f"{height}:progress"] = glyph("تقدّمك نحو المكافأة", arabic, True)
    masks[f"{height}:ready"] = glyph("مكافأتك جاهزة", arabic, True)

output = """// Generated by scripts/build-wallet-type.py from bundled OFL Readex Pro fonts.
const GLYPHS=__GLYPHS__;
const cache=new Map();
export async function walletGlyph(height, text) {
  const key=height+':'+text, info=GLYPHS[key];
  if (!info) throw new Error('Unknown wallet glyph');
  if (!cache.has(key)) {
    const promise=(async()=>{
      const bytes=Uint8Array.from(atob(info.data),c=>c.charCodeAt(0));
      const data=new Uint8Array(await new Response(new Blob([bytes]).stream().pipeThrough(new DecompressionStream('deflate'))).arrayBuffer());
      return {w:info.w,h:info.h,data};
    })();
    cache.set(key,promise);
    promise.catch(()=>{if(cache.get(key)===promise)cache.delete(key);});
  }
  return cache.get(key);
}
""".replace("__GLYPHS__", json.dumps(masks, separators=(",", ":")))
(ROOT / "src/wallet-type.js").write_text(output)
print("Generated wallet-type.js:", len(output), "bytes")
